<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>TrafficSignRecognitionProject</RootNamespace>
    <ApplicationIcon>Assets/WindowIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <PublishProfile>Properties\PublishProfiles\win10-$(Platform).pubxml</PublishProfile>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\Limit100.jpg" />
    <None Remove="Assets\Limit110.png" />
    <None Remove="Assets\Limit120.jpg" />
    <None Remove="Assets\Limit20.jpg" />
    <None Remove="Assets\Limit30.jpg" />
    <None Remove="Assets\Limit50.png" />
    <None Remove="Assets\Limit60.jpg" />
    <None Remove="Assets\Limit70.png" />
    <None Remove="Assets\Limit80.jpg" />
    <None Remove="Assets\SignCatalogue\BicyclePath.png" />
    <None Remove="Assets\SignCatalogue\LeftCurve.png" />
    <None Remove="Assets\SignCatalogue\Limit100.png" />
    <None Remove="Assets\SignCatalogue\Limit120.png" />
    <None Remove="Assets\SignCatalogue\Limit20.png" />
    <None Remove="Assets\SignCatalogue\Limit30.png" />
    <None Remove="Assets\SignCatalogue\Limit60.png" />
    <None Remove="Assets\SignCatalogue\Limit80.png" />
    <None Remove="Assets\SignCatalogue\MultipleCurves.png" />
    <None Remove="Assets\SignCatalogue\NoOvertaking.png" />
    <None Remove="Assets\SignCatalogue\NoStopping.png" />
    <None Remove="Assets\SignCatalogue\NoTurnLeft.png" />
    <None Remove="Assets\SignCatalogue\OneWayRoad.png" />
    <None Remove="Assets\SignCatalogue\OtherDangers.png" />
    <None Remove="Assets\SignCatalogue\Parking.png" />
    <None Remove="Assets\SignCatalogue\PassEitherSide.png" />
    <None Remove="Assets\SignCatalogue\PassLeft.png" />
    <None Remove="Assets\SignCatalogue\PassRight.png" />
    <None Remove="Assets\SignCatalogue\PedestrianCrossing.png" />
    <None Remove="Assets\SignCatalogue\PedestrianCrossingWarning.png" />
    <None Remove="Assets\SignCatalogue\Priority.png" />
    <None Remove="Assets\SignCatalogue\Roadworks.png" />
    <None Remove="Assets\SignCatalogue\Roundabout.png" />
    <None Remove="Assets\SignCatalogue\SemaphoreGreen.png" />
    <None Remove="Assets\SignCatalogue\SemaphoreGreenArrow.png" />
    <None Remove="Assets\SignCatalogue\SemaphoreRed.png" />
    <None Remove="Assets\SignCatalogue\SlipperyRoad.png" />
    <None Remove="Assets\SignCatalogue\Speedbump.png" />
    <None Remove="Assets\SignCatalogue\Stop.png" />
    <None Remove="Assets\SignCatalogue\StraightLeft.png" />
    <None Remove="Assets\SignCatalogue\TurnLeftAfter.png" />
    <None Remove="Assets\SignCatalogue\TurnRightAfter.png" />
    <None Remove="Assets\SignCatalogue\TwoWayTraffic.png" />
    <None Remove="Assets\SignCatalogue\WrongWay.png" />
    <None Remove="Assets\SignCatalogue\yield.png" />
    <None Remove="Assets\Square150x150Logo.scale-200.png" />
    <None Remove="Assets\Square44x44Logo.scale-200.png" />
    <None Remove="Assets\WindowIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Animations" Version="7.1.2" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
    <PackageReference Include="CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.1.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.251106002" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="3.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="WinUIEx" Version="2.9.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="requirements.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\config.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\dataset.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\loss.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\model.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\predict.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\testing.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\train.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\utils.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch10.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch100.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch15.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch20.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch25.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch30.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch35.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch40.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch45.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch5.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch50.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch55.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch60.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch65.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch70.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch75.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch80.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch85.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch90.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\ML\weights\yolov1_epoch95.pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Testing\frame_extractor.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Testing\reconstruct_video.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Testing\run_inference.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Training\dataset_preparator.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\Training\video_cutter.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Scripts\sign_labels.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Page Update="Views\TrainPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>
